services:

  OpenPlanningPoker.UserManagement.GraphQL:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://162.55.213.9:3100
    ports:
      - "9090:8080"

  OpenPlanningPoker.GameEngine.GraphQL:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://162.55.213.9:3100
    ports:
      - "9091:8080"

  openplanningpoker.fusion.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://162.55.213.9:3100
    ports:
      - 10010:8080
      - 10011:8081

  openplanning.poker.webapp:
    ports:
      - 10000:80

  opp-db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  OpenPlanningPoker.Cache:
    ports:
      - 6379:6379
