version: '3.8'

services:
  OpenPlanningPoker.GameEngine.GraphQL:
    image: ${DOCKER_REGISTRY-}openplanningpokergameenginegraphql
    container_name: OpenPlanningPoker.GameEngine.GraphQL
    build:
      context: .
      dockerfile: src/GameEngine/OpenPlanningPoker.GameEngine.GraphQL/Dockerfile
    depends_on:
      - opp-db

  OpenPlanningPoker.UserManagement.GraphQL:
    image: ${DOCKER_REGISTRY-}openplanningpokerusermanagementgraphql
    container_name: OpenPlanningPoker.UserManagement.GraphQL
    build:
      context: .
      dockerfile: src/UserManagement/OpenPlanningPoker.UserManagement.GraphQL/Dockerfile

  opp-db:
    image: postgres:15.5
    container_name: OpenPlanningPoker.Db
