global using System.Reflection;
global using OpenPlanningPoker.GameEngine.Application.Paging;
global using OpenPlanningPoker.GameEngine.Domain.Abstractions;
global using OpenPlanningPoker.GameEngine.Infrastructure;
global using FluentValidation;
global using NetArchTest.Rules;
global using MediatR;
global using Shouldly;
global using Xunit;