name: Deploy OPP
run-name: "Deploying Open Planning Poker Game - Build #${{ github.run_number }}"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy-opp-user-management:
    name: Deploy OPP User Management
    uses: ./.github/workflows/deploy-opp-user-management.yaml
    secrets: inherit

  deploy-opp-game-engine:
    name: Deploy OPP Game Engine
    uses: ./.github/workflows/deploy-opp-game-engine.yaml

  deploy-opp-ui:
    name: Deploy OPP UI
    needs: [deploy-opp-user-management, deploy-opp-game-engine]
    uses: ./.github/workflows/deploy-opp.yaml
