name: Deploy OPP Services
run-name: "Deploying Open Planning Poker Services to server"
on:
  push:
    branches:
      - main
      - op-gw
    workflow_dispatch:
jobs:
  permissions:
      contents: read
      packages: write
  opp-user-management:
    uses: ./.github/workflows/deploy-opp-user-management.yaml

  opp-game-engine:
    uses: ./.github/workflows/deploy-opp-game-engine.yaml

  opp-gateway:
    needs: [opp-user-management, opp-game-engine]
    uses: ./.github/workflows/deploy-opp-gateway.yaml