name: Deploy OPP Gateway
run-name: "Deploying Open Planning Poker Gateway to server"
on: 
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
jobs:
  deploy-opp-gateway:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Set connection string in appsettings.json
        run: |
          jq '.Cors.AllowedOrigins = ${{ vars.OPP_DEFAULT_CORS }} |
              .Otel.Endpoint = "${{ vars.OTEL_ENDPOINT }}" |
              .Serilog.WriteTo[0].Args.uri = "${{ vars.LOKI_URL }}"
              ' ./backend/OpenPlanningPoker/src/Gateway/OpenPlanningPoker.Fusion.Gateway/appsettings.json > temp.json && mv temp.json ./backend/OpenPlanningPoker/src/Gateway/OpenPlanningPoker.Fusion.Gateway/appsettings.json

      - name: Install HotChocolate.Fusion CLI
        run: |
          dotnet tool install -g HotChocolate.Fusion.CommandLine

      - name: Pack User Management subgraph
        run: |
          cd backend/OpenPlanningPoker/src/UserManagement/OpenPlanningPoker.UserManagement.GraphQL
          jq '.http.baseAddress = "${{ vars.OPP_UM_SUBGRAPH_URL }}"' subgraph-config.json > temp.json && mv temp.json subgraph-config.json
          dotnet run -- schema export --output schema.graphql
          fusion subgraph pack
          cat subgraph-config.json

      - name: Pack Game Engine subgraph
        run: |
          cd backend/OpenPlanningPoker/src/GameEngine/OpenPlanningPoker.GameEngine.GraphQL
          jq '.http.baseAddress = "${{ vars.OPP_GE_SUBGRAPH_URL }}"' subgraph-config.json > temp.json && mv temp.json subgraph-config.json
          dotnet run -- schema export --output schema.graphql
          fusion subgraph pack
          cat subgraph-config.json

      - name: Compose Schema
        run: |
          cd backend/OpenPlanningPoker/src/Gateway/OpenPlanningPoker.Fusion.Gateway
          fusion compose -p gateway.fgp -s ../../UserManagement/OpenPlanningPoker.UserManagement.GraphQL/UserManagement.fsp
          fusion compose -p gateway.fgp -s ../../GameEngine/OpenPlanningPoker.GameEngine.GraphQL/GameEngine.fsp
          cat gateway.fgp

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          cd backend/OpenPlanningPoker
          docker build -t openplanningpokergatewaygraphql:latest -f ./src/Gateway/OpenPlanningPoker.Fusion.Gateway/Dockerfile .

      - name: Build and push Docker image
        run: |
          cd backend/OpenPlanningPoker
          docker build -t ghcr.io/${{ github.repository_owner }}/openplanningpokergatewaygraphql:latest -f ./src/Gateway/OpenPlanningPoker.Fusion.Gateway/Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/openplanningpokergatewaygraphql:latest

      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository_owner }}/openplanningpokergatewaygraphql:latest
            docker rm -f OpenPlanningPoker.Fusion.Gateway || true
            docker run -d \
              --name OpenPlanningPoker.Fusion.Gateway \
              --network oppnetwork \
              -e ASPNETCORE_ENVIRONMENT=Development \
              -e ASPNETCORE_HTTP_PORTS=8080 \
              -e OTEL_EXPORTER_OTLP_ENDPOINT=${{ vars.LOKI_URL }} \
              -p 10010:8080 \
              -p 10011:8081 \
              ghcr.io/${{ github.repository_owner }}/openplanningpokergatewaygraphql:latest
