name: Deploy OPP UI
run-name: "Deploying Open Planning Poker UI - Build #${{ github.run_number }}"
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SSH_PASSWORD: 
        required: true
jobs:
  deploy-opp-ui:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set connection string in config.json
        working-directory: frontend/open-planning-poker-web-app
        run: |
          jq '.gqlGateway = "${{ vars.OPP_API_URL }}" |
              .gqlGatewayWss = "${{ vars.OPP_WSS_URL }}"
             ' ./public/assets/config.json > temp.json && mv temp.json ./public/assets/config.json
      
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        working-directory: frontend/open-planning-poker-web-app
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/openplanningpokerui:${{ github.run_number }} -f ./Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/openplanningpokerui:${{ github.run_number }}

          docker build -t ghcr.io/${{ github.repository_owner }}/openplanningpokerui:latest -f ./Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/openplanningpokerui:latest

      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository_owner }}/openplanningpokerui:${{ github.run_number }}
            docker rm -f OpenPlanningPoker.UI || true
            docker run -d \
              --name OpenPlanningPoker.UI \
              --network oppnetwork \
              -p 10000:80 \
              ghcr.io/${{ github.repository_owner }}/openplanningpokerui:${{ github.run_number }}
