name: Deploy OPP Services
run-name: "Deploying Open Planning Poker Services to server"
on:
  push:
    branches:
      - main
      - op-gw
    workflow_dispatch:
permissions:
    contents: read
    packages: write
jobs:
  opp-user-management:
    name: Deploy OPP User Management
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      password: ${{ secrets.SSH_PASSWORD }}
    uses: ./.github/workflows/deploy-opp-user-management.yaml

  opp-game-engine:
    name: Deploy OPP Game Engine
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      password: ${{ secrets.SSH_PASSWORD }}
    uses: ./.github/workflows/deploy-opp-game-engine.yaml

  opp-gateway:
    name: Deploy OPP Gateway
    needs: [opp-user-management, opp-game-engine]
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      password: ${{ secrets.SSH_PASSWORD }}
    uses: ./.github/workflows/deploy-opp-gateway.yaml