name: Deploy Redis
run-name: "Deploying Redis to server"
on:
  workflow_dispatch:
jobs:
  deploy-redis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_PRIVATE_HOST }}
          username: ${{ vars.SSH_PRIVATE_USER }}
          password: ${{ secrets.SSH_PRIVATE_PASSWORD }}
          script: |
            docker pull redis:latest
            docker rm -f OpenPlanningPoker.Cache || true
            docker run -d --name OpenPlanningPoker.Cache --network oppnetwork -p 6379:6379 redis:latest
            docker system prune -f
