name: Deploy OPP
run-name: "Deploying Open Planning Poker Game - Build #${{ github.run_number }}"
on:
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  deploy-opp-user-management:
    name: Deploy OPP User Management
    uses: ./.github/workflows/deploy-opp-user-management.yaml
    secrets: 
      GITHUB_TOKEN: ${{ secrets.SSH_PASSWORD }}
  deploy-opp-game-engine:
    name: Deploy OPP Game Engine
    uses: ./.github/workflows/deploy-opp-game-engine.yaml
    secrets: 
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD  }}
      GITHUB_TOKEN: ${{ secrets.SSH_PASSWORD }}
  deploy-opp-ui:
    name: Deploy OPP UI
    needs: [deploy-opp-user-management, deploy-opp-game-engine]
    uses: ./.github/workflows/deploy-opp-ui.yaml
    secrets: 
      GITHUB_TOKEN: ${{ secrets.SSH_PASSWORD }}
  deploy-opp-gateway:
    name: Deploy OPP Gateway
    needs: [deploy-opp-ui]
    uses: ./.github/workflows/deploy-opp-gateway.yaml
    secrets: 
      GITHUB_TOKEN: ${{ secrets.SSH_PASSWORD }}
