name: Deploy PostgreSQL
run-name: "Deploying PostgreSQL to server"
on:
  workflow_dispatch:
jobs:
  deploy-postgresql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull postgres:15.5
            docker rm -f OpenPlanningPoker.Db || true
            docker run -d \
              --name OpenPlanningPoker.Db \
              --network oppnetwork \
              -e POSTGRES_DB=${{ vars.POSTGRES_DB }} \
              -e POSTGRES_USER=${{ vars.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -v /path/to/database:/var/lib/postgresql/data \
              -p 5432:5432 \
              postgres:15.5
            docker system prune -f
