name: Deploy OPP
run-name: "Deploying Open Planning Poker Game - Build #${{ github.run_number }}"
on:
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  opp-um:
    name: Deploy OPP User Management
    uses: ./.github/workflows/deploy-opp-user-management.yaml
    secrets: 
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  opp-ge:
    name: Deploy OPP Game Engine
    uses: ./.github/workflows/deploy-opp-game-engine.yaml
    secrets: 
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD  }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  opp-graphql-gtw:
    name: Deploy OPP GraphQL Gateway
    needs: [opp-um, opp-ge]
    uses: ./.github/workflows/deploy-opp-gateway.yaml
    secrets: 
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  opp-gtw:
    name: Deploy OPP API Gateway
    needs: [opp-graphql-gtw]
    uses: ./.github/workflows/deploy-opp-yarp-gateway.yaml
    secrets: 
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  opp-ui:
    name: Deploy OPP UI
    needs: [opp-gtw]
    uses: ./.github/workflows/deploy-opp-ui.yaml
    secrets: 
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
