name: Deploy OPP User Management
run-name: "Deploying Open Planning Poker User Management to server"
on: 
  push:
    branches:
      - main
      - deploy-um
  workflow_dispatch:
jobs:
  deploy-opp-user-management:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Set connection string in appsettings.json
        run: |
          # Replace placeholders in appsettings.json with GitHub secrets
          jq '.ConnectionStrings.Cache = "${{ secrets.REDIS_HOST }}" |
              .Cors.AllowedOrigins = ${{ secrets.OPP_DEFAULT_CORS }} |
              .Otel.Endpoint = "${{ secrets.OTEL_ENDPOINT }}" |
              .Serilog.WriteTo[0].Args.uri = "${{ secrets.LOKI_URL }}"
              ' ./backend/OpenPlanningPoker/src/UserManagement/OpenPlanningPoker.UserManagement.GraphQL/appsettings.json > temp.json && mv temp.json ./backend/OpenPlanningPoker/src/UserManagement/OpenPlanningPoker.UserManagement.GraphQL/appsettings.json

      - name: Build Docker image
        run: |
          cd backend/OpenPlanningPoker
          ls
          docker build -t openplanningpokerusermanagementgraphql:latest -f ./src/UserManagement/OpenPlanningPoker.UserManagement.GraphQL/Dockerfile .

      - name: Save Docker image as tar
        run: |
          docker save -o openplanningpokerusermanagementgraphql.tar openplanningpokerusermanagementgraphql:latest

      - name: Transfer image to the server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            ls
            mkdir -p /tmp/docker-images
            scp -o StrictHostKeyChecking=no openplanningpokerusermanagementgraphql.tar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/tmp/

      - name: Load Docker image on the server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker load -i /tmp/docker-images/openplanningpokerusermanagementgraphql.tar

      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker rm -f OpenPlanningPoker.UserManagement.GraphQL || true
            docker run -d \
              --name OpenPlanningPoker.UserManagement.GraphQL \
              -e ASPNETCORE_ENVIRONMENT=Development \
              -e ASPNETCORE_HTTP_PORTS=8080 \
              -e OTEL_EXPORTER_OTLP_ENDPOINT=${{ secrets.LOKI_URL }} \
              -p 9091:8080 \
              openplanningpokerusermanagementgraphql:latest