name: Publish Open Planning Poker NuGet Package
run-name: "Publishing Open Planning Poker NuGet Package - Build #${{ github.run_number }}"
on:
  workflow_dispatch:
jobs:
  publish-open-planning-poker-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        working-directory: backend/open-planning-poker-shared
        run: dotnet restore

      - name: Build project
        working-directory: backend/open-planning-poker-shared
        run: dotnet build -c Release --no-restore

      - name: Pack NuGet package
        working-directory: backend/open-planning-poker-shared
        run: dotnet pack -c Release --no-build --output .

      - name: Publish to NuGet.org
        working-directory: backend/open-planning-poker-shared
        run: dotnet nuget push "*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_ORG_API_KEY }} --skip-duplicate